# Generated by Django 4.2.4 on 2023-11-13 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="TechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(max_length=300)),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("study", "study"), ("project", "project")],
                        default="study",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "online"), ("offline", "offline")],
                        default="online",
                        max_length=10,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("1 개월", "1 개월"),
                            ("2 개월", "2 개월"),
                            ("3 개월", "3 개월"),
                            ("4 개월", "4 개월"),
                            ("5 개월", "5 개월"),
                            ("6 개월", "6 개월"),
                            ("1 년 이상", "1 년 이상"),
                        ],
                        default="1 개월",
                        max_length=10,
                    ),
                ),
                ("deadline", models.DateField()),
                ("kakao", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("views", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.ManyToManyField(to="api.position")),
                ("recruit", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
